export { DifferentiatorsSection } from './differentiators-section'
export { FaqSection } from './faq-section'
export { FeaturesTabsSection } from './features-tabs-section'
export { HeroSection } from './hero-section'
export { IndustriesSection } from './industries-section'
export { IntroSection, TrustMarqueeSection } from './intro-section'
export { LogosMarqueeSection } from './logos-marquee-section'
export { PlatformSection } from './platform-section'
export { TestimonialsSection } from './testimonials-section'
export { TransformationSection } from './transformation-section'
export { WhyTeamsChooseSection } from './why-teams-choose-section'

/** Legacy sections — kept for reference, not used on homepage. */
export { AudienceSection } from './audience-section'
export { ProblemSection } from './problem-section'
export { ProcessSection } from './process-section'
export { WhyChooseSection } from './why-choose-section'
export { WorkspaceProofSection } from './workspace-proof-section'
